In [1]:
import numpy as np

In [2]:
def f(x, y, b):
    return (b[0] + b[1]*x + b[2]*x**2 - y)

def res(x, y, b):
    return sum(f(x,y, b)*f(x, y, b))

# Elementary form of gradient
def grad(x, y, b):
    n = len(x)
    return np.array([
            sum(f(x, y, b)),
            sum(x*f(x, y, b)),
            sum(x**2*f(x, y, b))
    ])

# Matrix form of gradient
def grad_m(X, y, b):
    return X.T@X@b- X.T@y

In [3]:
x = np.arange(10)
y = np.array([  1.58873597,   7.55101533,  10.71372171,   7.90123225,
                -2.05877605, -12.40257359, -28.64568712, -46.39822281,
                -68.15488905, -97.16032044])

In [4]:
grad(x, y, np.zeros(3))

array([  227.0657638 ,  1933.9094954 , 15758.14427298])

In [5]:
X = np.c_[np.ones(len(x)), x, x**2]
grad_m(X, y, np.zeros(3))

array([  227.0657638 ,  1933.9094954 , 15758.14427298])

In [6]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
y

array([  1.58873597,   7.55101533,  10.71372171,   7.90123225,
        -2.05877605, -12.40257359, -28.64568712, -46.39822281,
       -68.15488905, -97.16032044])

In [8]:
b = grad(x, y, np.zeros(3))

In [9]:
grad(x, y, b)

array([4.58059477e+06, 3.24735582e+07, 2.45616265e+08])

In [10]:
X

array([[ 1.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 1.,  2.,  4.],
       [ 1.,  3.,  9.],
       [ 1.,  4., 16.],
       [ 1.,  5., 25.],
       [ 1.,  6., 36.],
       [ 1.,  7., 49.],
       [ 1.,  8., 64.],
       [ 1.,  9., 81.]])

In [14]:
from scipy.linalg import solve

beta1 = solve(X.T@X, X.T@y)
beta1

array([ 2.55079998,  7.31478229, -2.04118936])

In [16]:
max_iter = 10000

In [17]:
a = 0.0001
beta2 = np.zeros(3)
for i in range(max_iter):
    beta2 -= a * grad(x, y, beta2)
beta2

array([ 2.73391723,  7.23152392, -2.03359658])